// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duvqdpyxrkdmoyizepqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1dnFkcHl4cmtkbW95aXplcHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NDY2MTIsImV4cCI6MjA1NjQyMjYxMn0.3g2BQ5Jnc42MXtMsk-5bMIEpxRTW82-LttJfQ61cHck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);